Add bin to /Users/scrogson/.dotfiles/bin:./node_modules/.bin:/usr/local/share/python:/usr/local/bin:/Users/scrogson/.rvm/gems/ruby-1.9.3-p392/bin:/Users/scrogson/.rvm/gems/ruby-1.9.3-p392@global/bin:/Users/scrogson/.rvm/rubies/ruby-1.9.3-p392/bin:/Users/scrogson/.rvm/bin:/Users/scrogson/.dotfiles/bin:./node_modules/.bin:/usr/local/share/python:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:./node_modules/.bin:/usr/local/share/python:/usr/local/sbin:/usr/local/sbin:/usr/sbin:/sbin:/Users/scrogson/.rvm/bin:/usr/local/sbin:/usr/sbin:/sbin:/Users/scrogson/.rvm/bin; Replace battery script; Add spark script

diff --git a/bin/battery b/bin/battery
--- a/bin/battery
+++ b/bin/battery
@@ -1,40 +1,146 @@
-#!/usr/bin/env python
-# coding=UTF-8
+#!/bin/sh
 
-import math, subprocess
+# Author: Nicolas Goles
+# url: https://github.com/Goles/Battery
 
-p = subprocess.Popen(["ioreg", "-rc", "AppleSmartBattery"], stdout=subprocess.PIPE)
-output = p.communicate()[0]
+battery_charge()
+{
+    ioreg -c AppleSmartBattery -w0 | \
+    grep -o '"[^"]*" = [^ ]*' | \
+    sed -e 's/= //g' -e 's/"//g' | \
+    sort | \
+    while read key value; do
+        case $key in
+            "MaxCapacity")
+                export maxcap=$value;;
+            "CurrentCapacity")
+                export curcap=$value;;
+        esac
+        if [[ -n "$maxcap" && -n $curcap ]]; then
+            CAPACITY=$(( 100 * curcap / maxcap))
+            printf "%d" $CAPACITY
+            break
+        fi
+    done
+}
 
-o_max = [l for l in output.splitlines() if 'MaxCapacity' in l][0]
-o_cur = [l for l in output.splitlines() if 'CurrentCapacity' in l][0]
+#
+# Run Battery
+#
 
-b_max = float(o_max.rpartition('=')[-1].strip())
-b_cur = float(o_cur.rpartition('=')[-1].strip())
+BATTERY_STATUS=`battery_charge`
+[ -z "$BATTERY_STATUS" ] && exit
 
-charge = b_cur / b_max
-charge_threshold = int(math.ceil(10 * charge))
+#
+# Read args
+#
 
-# Output
+while getopts ":g:m:w:o:h" opt; do
+  case $opt in
+    g)
+      if [ "$good_color" == "" ]; then
+        good_color=$OPTARG
+      fi
+      ;;
+    m)
+      if [ "$middle_color" == "" ]; then
+        middle_color=$OPTARG
+      fi
+      ;;
+    w)
+      if [ "$warn_color" == "" ]; then
+        warn_color=$OPTARG
+      fi
+      ;;
+    o)
+      if [ "$output" == "" ]; then
+        output=$OPTARG
+      fi
+      ;;
+    h)
+      echo "Usage: battery [-g good battery status color, default green or 1;32] [-m middle battery status color, default yellow or 1;33] [-w warn batttery status color, default red or 0;31] [-o specifies output format, use -o tmux to specify tmux status bar format]"
+      exit 0
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG"
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument"
+      exit 1
+      ;;
+  esac
+done
 
-total_slots, slots = 10, []
-filled = int(math.ceil(charge_threshold * (total_slots / 10.0))) * u'▸'
-empty = (total_slots - len(filled)) * u'▹'
+tmux=false
 
-out = (filled + empty).encode('utf-8')
-import sys
+if [ "$output" == "tmux" ]; then
+  tmux=true
+fi
 
-color_green = '%{
-r_yellow = '%{
-r_red = '%{
-r_reset = '%{
-r_out = (
-    color_green if len(filled) > 6
-    else color_yellow if len(filled) > 4
-    else color_red
-)
+#
+# For default behavior when no different colors are specified
+#
 
-out = color_out + out + color_reset
-sys.stdout.write(out)
+if [ "$good_color" == "" ]; then
+  case "$tmux" in
+    true) good_color="green" ;;
+    false) good_color="1;32" ;;
+  esac
+fi
 
-# vim: ft=python
+if [ "$middle_color" == "" ]; then
+  case "$tmux" in
+    true) middle_color="yellow" ;;
+    false) middle_color="1;33" ;;
+  esac
+fi
+
+if [ "$warn_color" == "" ]; then
+  case "$tmux" in
+    true) warn_color="red" ;;
+    false) warn_color="0;31" ;;
+  esac
+fi
+
+#
+# Apply the correct color to the battery status prompt
+#
+
+if [ $BATTERY_STATUS -ge 75 ]; then
+
+    # Green
+    case "$tmux" in
+        true) COLOR="#[fg=$good_color]" ;;
+        false) COLOR=$good_color ;;
+    esac
+
+elif [ $BATTERY_STATUS -ge 25 ] && [ $BATTERY_STATUS -lt 75 ]; then
+
+    # Yellow
+    case "$tmux" in
+        true) COLOR="#[fg=$middle_color]" ;;
+        false) COLOR=$middle_color ;;
+    esac
+
+elif [ $BATTERY_STATUS -lt 25 ]; then
+
+    # Red
+    case "$tmux" in
+        true) COLOR="#[fg=$warn_color]" ;;
+        false) COLOR=$warn_color ;;
+    esac
+
+fi
+
+#
+# Print the battery status
+#
+
+GRAPH=$(spark 0 ${BATTERY_STATUS} 100 | awk '{print substr($0,4,3)}')
+
+if [ "$tmux" == "false" ]; then
+    printf "\e[0;%sm%s %s \e[m\n"  "$COLOR" "[$BATTERY_STATUS%]"  "$GRAPH"
+else
+    printf "%s%s %s" "$COLOR" "[$BATTERY_STATUS%]" "$GRAPH"
+fi
